CREATE TABLE GSS_ORDER(
ROW_ID NUMBER,
ORDER_ID VARCHAR2(50 CHAR),
ORDER_DATE DATE,
SHIP_DATE DATE,
SHIP_TYPE VARCHAR2(15 CHAR),
CUSTOMER_ID VARCHAR2(30 CHAR),
CUSTOMER_NAME VARCHAR2(100 CHAR),
MARGET_SEGMENT VARCHAR2(30 CHAR),
POST_CODE VARCHAR2(15 CHAR),
CITY VARCHAR2(50 CHAR),
PROVINCE VARCHAR2(50 CHAR),
COUNTRY VARCHAR2(50 CHAR),
REGION VARCHAR2(50 CHAR),
MARKET VARCHAR2(50 CHAR),
PROD_ID VARCHAR2(30 CHAR),
PROD_TYPE VARCHAR2(30 CHAR),
PROD_SUB_TYPE VARCHAR2(30 CHAR),
PROD_NAME VARCHAR2(200 CHAR),
SALE NUMBER,
QUANTITY NUMBER,
DISCOUNT NUMBER,
PROFIT NUMBER,
SHIP_COST NUMBER,
ORDER_LEVEL VARCHAR2(15 CHAR)
);

CREATE TABLE GSS_RETURNED_ORDER(
ORDER_ID VARCHAR2(50 CHAR),
REGION VARCHAR2(30 CHAR),
RETURNED VARCHAR2(1 CHAR)
);

CREATE TABLE GSS_STAFF(
NAME VARCHAR2(50 CHAR),
REGION VARCHAR(30 CHAR)
);